# Module 2 - Project Proposal
Ishrak Rahman

In [33]:
import pandas as pd
data = pd.read_csv("house_price_bd.csv")

In [70]:
data.sample(10)

,Title,Bedrooms,Bathrooms,Floor_no,Occupancy_status,Floor_area,City,Price_in_taka,Location
3291,"Plot Of 5 Katha Is Up For Sale In Narayanganj,...",NaN,NaN,NaN,vacant,3600.0,narayanganj-city,"৳7,625,000","Rupganj, Narayanganj"
2118,All Set For Selling Purpose This 1485 Sq Ft Fl...,3.0,4.0,2,vacant,1485.0,chattogram,"৳12,000,000","Jubilee Road, 22 No. Enayet Bazaar Ward"
3265,"In The Location Of Bproperty Village ,Rupganj ...",NaN,NaN,NaN,vacant,2160.0,narayanganj-city,"৳3,375,000","Rupganj, Narayanganj"
2001,"In Halishahar Near Navy Hospital, A 110 Sq. Ft...",NaN,NaN,NaN,vacant,110.0,chattogram,"৳2,750,000","39 No. South Halishahar Ward, Halishahar"
3100,A 1180 Sq Ft Flat Is Up For Sale In A Well Sec...,3.0,3.0,6,vacant,1180.0,chattogram,"৳7,500,000","Abdullah Khan Road, Sholokbahar"
3244,"Positioned At Thakur Para, 1350 Sq Ft Resident...",3.0,3.0,5,vacant,1350.0,cumilla,"৳5,130,000","South Thakur Para, Thakur Para"
3778,800 Sq Ft Apartment Is Available For Sale In T...,2.0,1.0,3,vacant,800.0,gazipur,"৳2,560,000","Tongi, Gazipur Sadar Upazila"
2713,163 Square Feet Commercial Shop For Sale At Ju...,NaN,NaN,NaN,vacant,163.0,chattogram,"৳11,410,000","Jubilee Road, 22 No. Enayet Bazaar Ward"
274,Modern 1150 Sq Ft Flat For Sale In Badda,3.0,3.0,3,vacant,1150.0,dhaka,"৳8,800,000","Middle Badda, Badda"
2116,An Amazing Flat Is Ready For Sale At Nasirabad...,3.0,3.0,4,vacant,1520.0,chattogram,"৳16,000,000","Nasirabad, 15 No. Bagmoniram Ward"

In [71]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3865 entries, 0 to 3864
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             3865 non-null   object
 1   Bedrooms          2864 non-null   float64
 2   Bathrooms         2864 non-null   float64
 3   Floor_no          3181 non-null   object
 4   Occupancy_status  3766 non-null   object
 5   Floor_area        3766 non-null   float64
 6   City              3865 non-null   object
 7   Price_in_taka     3865 non-null   object
 8   Location          3859 non-null   object
dtypes: float64(3), object(6)
memory usage: 271.9+ KB